import type { DesignSystem } from "./types";

export const sampleSystem: DesignSystem = {
  name: "Mirabelle Design System",
  tokenGroups: [
    {
      name: "Colors",
      tokens: [
        { name: "mirabelle-ds-background", value: "#ffffff", type: "color", description: "Page background" },
        { name: "mirabelle-ds-surface", value: "#f7f9f8", type: "color", description: "Card and panel surfaces" },
        { name: "mirabelle-ds-surface-alt", value: "#ecf1ef", type: "color", description: "Alternate surface, muted backgrounds" },
        { name: "mirabelle-ds-primary", value: "#5c756c", type: "color", description: "Primary brand, CTAs, active states" },
        { name: "mirabelle-ds-primary-hover", value: "#475c55", type: "color", description: "Primary hover state" },
        { name: "mirabelle-ds-primary-text", value: "#ffffff", type: "color", description: "Text on primary surfaces" },
        { name: "mirabelle-ds-text", value: "#1a1a1a", type: "color", description: "Primary text" },
        { name: "mirabelle-ds-text-secondary", value: "#575958", type: "color", description: "Secondary text, descriptions" },
        { name: "mirabelle-ds-text-muted", value: "#617e74", type: "color", description: "Muted text, hints" },
        { name: "mirabelle-ds-border", value: "#c5d3cd", type: "color", description: "Default borders" },
        { name: "mirabelle-ds-border-light", value: "#dfe7e4", type: "color", description: "Subtle borders, dividers" },
        { name: "mirabelle-ds-success", value: "#009183", type: "color", description: "Success states" },
        { name: "mirabelle-ds-warning", value: "#d36f6d", type: "color", description: "Warning states" },
        { name: "mirabelle-ds-error", value: "#d70025", type: "color", description: "Error states, destructive actions" },
        { name: "mirabelle-ds-info", value: "#008691", type: "color", description: "Informational states" },
      ],
    },
    {
      name: "Dark Mode",
      tokens: [
        { name: "mirabelle-ds-background-dark", value: "#121212", type: "color", description: "Page background (dark)" },
        { name: "mirabelle-ds-surface-dark", value: "#2a2b2b", type: "color", description: "Card surfaces (dark)" },
        { name: "mirabelle-ds-surface-alt-dark", value: "#3c3c3c", type: "color", description: "Alternate surface (dark)" },
        { name: "mirabelle-ds-primary-dark", value: "#95b1a6", type: "color", description: "Primary brand (dark, lighter for contrast)" },
        { name: "mirabelle-ds-primary-hover-dark", value: "#aac0b8", type: "color", description: "Primary hover (dark)" },
        { name: "mirabelle-ds-text-dark", value: "#e8e8e8", type: "color", description: "Primary text (dark)" },
        { name: "mirabelle-ds-text-secondary-dark", value: "#c4c5c4", type: "color", description: "Secondary text (dark)" },
        { name: "mirabelle-ds-border-dark", value: "#4e4f4e", type: "color", description: "Borders (dark)" },
      ],
    },
    {
      name: "Typography",
      tokens: [
        { name: "mirabelle-ds-font-family-sans", value: "'DM Sans', 'Noto Sans', system-ui, sans-serif", type: "typography", description: "Primary typeface, Noto Sans fallback" },
        { name: "mirabelle-ds-font-family-mono", value: "'IBM Plex Mono', monospace", type: "typography", description: "Code, technical content" },
        { name: "mirabelle-ds-font-size-xs", value: "0.75rem", type: "typography", description: "Disclaimers only" },
        { name: "mirabelle-ds-font-size-sm", value: "0.875rem", type: "typography", description: "Minimum body text, labels" },
        { name: "mirabelle-ds-font-size-base", value: "1rem", type: "typography", description: "Default body" },
        { name: "mirabelle-ds-font-size-md", value: "1.125rem", type: "typography", description: "Large body, subheadings" },
        { name: "mirabelle-ds-font-size-lg", value: "1.25rem", type: "typography", description: "Section headings" },
        { name: "mirabelle-ds-font-size-xl", value: "1.5rem", type: "typography", description: "Page headings" },
        { name: "mirabelle-ds-font-size-2xl", value: "1.875rem", type: "typography", description: "Hero headings" },
        { name: "mirabelle-ds-font-weight-regular", value: "400", type: "typography", description: "Body weight" },
        { name: "mirabelle-ds-font-weight-medium", value: "500", type: "typography", description: "Emphasis, labels" },
        { name: "mirabelle-ds-font-weight-semibold", value: "600", type: "typography", description: "Headings" },
        { name: "mirabelle-ds-font-weight-bold", value: "700", type: "typography", description: "Strong emphasis" },
        { name: "mirabelle-ds-line-height-tight", value: "1.1", type: "typography", description: "Headings" },
        { name: "mirabelle-ds-line-height-normal", value: "1.5", type: "typography", description: "Body text" },
        { name: "mirabelle-ds-line-height-relaxed", value: "1.7", type: "typography", description: "Long-form content" },
      ],
    },
    {
      name: "Spacing",
      tokens: [
        { name: "mirabelle-ds-space-1", value: "0.25rem", type: "spacing", description: "4px -- tight inline" },
        { name: "mirabelle-ds-space-2", value: "0.5rem", type: "spacing", description: "8px -- small gaps" },
        { name: "mirabelle-ds-space-3", value: "0.75rem", type: "spacing", description: "12px -- default padding" },
        { name: "mirabelle-ds-space-4", value: "1rem", type: "spacing", description: "16px -- card padding" },
        { name: "mirabelle-ds-space-6", value: "1.5rem", type: "spacing", description: "24px -- section gaps" },
        { name: "mirabelle-ds-space-8", value: "2rem", type: "spacing", description: "32px -- large gaps" },
        { name: "mirabelle-ds-space-12", value: "3rem", type: "spacing", description: "48px -- page sections" },
        { name: "mirabelle-ds-space-16", value: "4rem", type: "spacing", description: "64px -- page-level" },
      ],
    },
    {
      name: "Radius",
      tokens: [
        { name: "mirabelle-ds-radius-xs", value: "0.375rem", type: "radius", description: "Small elements" },
        { name: "mirabelle-ds-radius-sm", value: "0.5rem", type: "radius", description: "Inputs, badges" },
        { name: "mirabelle-ds-radius-base", value: "0.75rem", type: "radius", description: "Default (cards, buttons)" },
        { name: "mirabelle-ds-radius-lg", value: "1.25rem", type: "radius", description: "Large cards, modals" },
        { name: "mirabelle-ds-radius-pill", value: "999px", type: "radius", description: "Pill shape" },
      ],
    },
    {
      name: "Motion",
      tokens: [
        { name: "mirabelle-ds-duration-fast", value: "120ms", type: "shadow", description: "Micro interactions" },
        { name: "mirabelle-ds-duration-normal", value: "180ms", type: "shadow", description: "Standard transitions" },
        { name: "mirabelle-ds-duration-slow", value: "280ms", type: "shadow", description: "Emphasis transitions" },
        { name: "mirabelle-ds-ease-standard", value: "cubic-bezier(0.2, 0.8, 0.2, 1)", type: "shadow", description: "Default easing" },
        { name: "mirabelle-ds-ease-emphasized", value: "cubic-bezier(0.2, 0, 0, 1)", type: "shadow", description: "Emphasis easing" },
      ],
    },
  ],
  components: [
    {
      name: "Button",
      description: "Primary interactive trigger. Pill-radius, min-height 2.75rem. Primary variant uses color-primary with white text, subtle hover lift.",
      variants: ["primary", "secondary", "ghost"],
      props: ["variant", "size", "disabled"],
    },
    {
      name: "Card",
      description: "Content container with backdrop-filter blur, subtle border, radius-lg. Optional elevated variant with shadow.",
      variants: ["default", "elevated"],
      props: ["elevated"],
    },
    {
      name: "Input",
      description: "Text input with border-light token, radius-base. Focus ring uses color-primary at 60% mix with white.",
      variants: ["default", "error", "disabled"],
      props: ["label", "placeholder", "error", "type"],
    },
    {
      name: "Badge",
      description: "Status indicator using surface-alt background. Used for tags, severity levels, and counts.",
      variants: ["default", "success", "warning", "error", "info"],
      props: ["variant", "size"],
    },
    {
      name: "Dialog",
      description: "Modal overlay with focus trap and keyboard dismissal. Uses overlay token for backdrop.",
      variants: ["default", "fullscreen"],
      props: ["open", "onClose", "title"],
    },
    {
      name: "Toast",
      description: "Temporary notification. Auto-dismisses. Uses semantic color tokens (success, warning, error, info).",
      variants: ["success", "error", "warning", "info"],
      props: ["variant", "duration", "dismissible"],
    },
  ],
};
